name: Hello world
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Build step
       run: echo "A demo build"
       
  test:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Test pahse
         run: echo "Running test cases"
         
  deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Deploy the App  
          run: echo "Deploying the app"
 
      
